package crm.call;
import jakarta.persistence.*;
import lombok.*;

import java.util.Date;

@Entity
@Table (name = "Call")
@Getter @Setter
@NoArgsConstructor //deleted @RequiredArgsConstructor because no requiredArgs
public class Call{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private int id;

    @Column(name = "timestamp")
    private Date timestamp;

    @Column(name = "type") //TODO ask if "autogenerated" values can't contain @notnull, @nonnull
    @Enumerated(value = EnumType.STRING)
    private Call.Type type;

    public enum Type{
        START, END
    }
}